#
# @lc app=leetcode id=3513 lang=python3
#
# [3513] Number of Unique XOR Triplets I
#

# @lc code=start
class Solution:
    def uniqueXorTriplets(self, nums: List[int]) -> int:
        n = len(nums)
        if n == 1:
            return 1
        if n == 2:
            return 2
        
        # For n >= 3, the set of values generated by XORing 3 elements
        # covers the entire range [0, 2^k - 1] where 2^k is the smallest
        # power of 2 greater than n.
        # This is because:
        # 1. We can form 0 using 1^2^3 = 0 (since n>=3).
        # 2. We can form any single number x as x^y^y.
        # 3. We can form any x^y as x^y^0 (and 0 is formable).
        # 4. The numbers 1 to n contain a basis for the vector space of 
        #    size 2^(bit_length). Specifically, 1, 2, 4, ... are all <= n.
        
        return 1 << n.bit_length()
# @lc code=end